### ISSUE TITLE
hey man, i like doushio so much, but i met some installation errors, please help me.

### ISSUE THREAD

**Issue by metalbug** [lalcmellkmal/doushio#92]
doushio look so good.
this is my first time to play nodejs.
i use the debian6 system and all doushio dependencies module.
but she can not run.
i would like to know more detailed installation tutorial.
and i do not like reCAPTCHA, how do i turn off this?
i have nodejs 0.8.14/0.8.17/0.9.6/0.10.32 will produce different error.
help me please...

some error like this:
npm WARN cannot run in wd doushio@0.3.1 make (wd=/home/wwwroot/doushio)
or this:
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:538:43)
    at Object.<anonymous> (/home/wwwroot/doushio/pipeline.js:20:6)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/wwwroot/doushio/server/state.js:8:16)
    at Module._compile (module.js:449:26)

**Comment by ElliotKa** [comment]
Hi bakape, seems like the script you wrote went 404. I'm also stuck on : 

0nii@ch4n:~/doushio$ node server/server.js

/home/0nii/doushio/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: Cannot find module './../tripcode/tripcode'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/0nii/doushio/server/server.js:21:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

I'm on Ubuntu 14.04 x64, Nodejs is v0.10.40 and i installed all the needed dependencies but still can't get it running, i'm not really experienced with nodejs so any help is welcome, thanks.

**Comment by bakape** [comment]
Yes, I simplified the installation on [my fork](https://github.com/bakape/meguca), so it became useless. For doushio issues consult lalcmellkmal.

**Comment by ElliotKa** [comment]
Thanks, i'll look into your fork today.
